create table libraryMM.book(
id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar,
author varchar,
year int);

create table librarymm.person(
id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar,
surname varchar,
patronymic varchar,
birth_year int);

create table librarymm.person_book(
person_id int REFERENCES person(id),
book_id   int REFERENCES book(id),
PRIMARY KEY(person_id, book_id));